name: Test Pull Request Commit

on: pull_request

jobs:
  test-pull-request-commit:

    runs-on: ubuntu-latest

    steps:
      - name: Queue pull request
        run: |
          curl -k -X POST 'https://${{ secrets.APPS_TEST_SERVER_URI }}/pull_request/' \
               -H 'Authorization: Bearer ${{ secrets.APPS_TEST_SERVER_API_KEY }}' \
               -d 'id=${{ github.event.pull_request.number }}' \
               -d 'requester=${{ github.event.pull_request.user.login }}' \
               --max-time 60
