name: Test Pull Request Commit

on:
  pull_request_target:
    paths:
      - 'Apps/**'

env:
  SCRIPTS_DIRECTORY: .github/workflows/scripts

jobs:
  test-pull-request-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo ::set-env name=PYTHON_REQUIREMENTS_FILE::${{ env.SCRIPTS_DIRECTORY }}/requirements.txt
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles(env.PYTHON_REQUIREMENTS_FILE) }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r ${{ env.PYTHON_REQUIREMENTS_FILE }}
      - name: Test pull request
        env:
          APPS_TEST_SERVER_URI: ${{ secrets.APPS_TEST_SERVER_URI }}
          APPS_TEST_SERVER_API_KEY: ${{ secrets.APPS_TEST_SERVER_API_KEY }}
        run: python ${{ env.SCRIPTS_DIRECTORY }}/test_pull_request.py \
                ${{ github.event.number }} \
                --requester '${{ github.event.sender.login }}'
